name: Criar arquivo

on:
  workflow_dispatch:

jobs:
  criar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Criar arquivo HTML
        run: |
          echo "<h1>Olá!</h1>" > novo.html

      - name: Salvar alteração
        run: |
          git add novo.html
          git commit -m "Criou novo arquivo"
          git push
